### PR TITLE
[semver:major] Make the default version of Go 1.18

### PR DESCRIPTION
**Pull request by glewis-ANet**
Update the default value of the Go version parameter to 1.18 in various places

### CODE REVIEW

**Comment by glewis-ANet** [comment]
We're now about 3 months into the Go 1.18 release.  Is it time?  Initially there were problems with linting, but those have either been fixed or the linter is disabling checks that remain broken.  The main driver beyond staying up to date is that this would allow us to try out Go generics.

**Comment by glewis-ANet** [comment]
Note that we could also decide this is a major version bump for the Orb if we consider the 1.18 update to be bigger than say 1.17.

**Review by xanderflood — APPROVED** [review]
LGTM and I'm agnostic about whether this is major or minor.

I do have a question that's been on my mind for a bit and that doesn't block this at all. In addition to these values here that are used when we compile, there's another go version designator in the go.mod of each project. The other value has some impact on the kinds of rules that are applied when tidying up, or which dependencies are kept hashed in go.sum. It's possible to supply a go version to the `go mod tidy` command, and the go.mod and go.sum contents differ as a result.

Since different go versions appear to have different expectations for dependency hashing, and since we don't always compile under the same version specified in our go.mod, is there a potential that, under certain edge cases when go-mod behavior changes, we might be leaving certain dependencies unlocked?

**Review by caeost — APPROVED** [review]

**Comment by xanderflood** [comment]
Oh there is another option! Always using the latest golang docker image doesn't prevent us from compiling against an earlier go version. We could write a small script that detects the go version (`go list -f {{.GoVersion}} -m`) and obtains the appropriate compiler via `go get`. I think that would allow us to freely change the version of the actual docker image while keeping a somewhat stronger guarantee of backwards-compatibility for our projects.

Anyways this is all just aimless discussion and definitely does not block your PR IMO!

**Comment by xanderflood** [comment]
I would point out that even though the language changes from 1.16 to 1.17 were not particularly large, IIRC that update (or maybe I'm thinking of a different one?) actually had a really profound impact on the contents of go.mod, significantly increasing the amount of information it tracked. So while I still don't think this entire domain contains much risk anyways, I don't think "does this seem like a big change to the language" has actually been a very useful indicator of whether there were significant changes in dependency tracking, which seems like it's the only area that really matters w.r.t. keeping these versions in sync.

**Pull request merged**
