### PR TITLE
[IN-433] Update default version of Go to 1.20

### PR DESCRIPTION
**Pull request by glewis-ANet**
1.18 is no longer supported, so switch to 1.20 as the default

### CODE REVIEW

**Comment by glewis-ANet** [comment]
I've run build/test/lint on a few services with 1.20.  I think we've got some lint errors that are starting to come up regardless of whether we actually do this update or not as the new version of golangci-lint is looking for things that have been newly deprecated in 1.20

**Comment by glewis-ANet** [comment]
I think we could handle this as a minor version update, but I'm open to it being a major version bump as well

**Comment by caeost** [comment]
> I think we could handle this as a minor version update, but I'm open to it being a major version bump as well

I think a minor bump could make sense since its a minor bump of golang but maybe that's a bit formulaic.

**Review by caeost — APPROVED** [review]

**Review by xanderflood — APPROVED** [review]
I agree, the go compilers within 1.x are meant to be fully backwards compatible I think, so this should be minor.

I guess the fact that we don't pin the golangci-lint version means we aren't really, since when golangci-lint introduces new rules, that's definitely not a backwards compatible change. I feel like maybe that's fine? But if we're okay with accepting that, then we should probably make sure our services never run lints prod deploys, since I don't think we'd want to apply new lint rules when pushing code that's already passed lints and QA.

That's all got nothing to do with this change though!

**Comment by glewis-ANet** [comment]
> I agree, the go compilers within 1.x are meant to be fully backwards compatible I think, so this should be minor.
> 
> I guess the fact that we don't pin the golangci-lint version means we aren't really doing strict semver, since when golangci-lint introduces new rules, that's definitely not a backwards compatible change. I feel like maybe that's fine? But if we're okay with accepting that, then we should probably make sure our services never run lints prod deploys, since I don't think we'd want to apply new lint rules when pushing code that's already passed lints and QA.
> 
> That's all got nothing to do with this change though!

So far we've been relatively lucky in that lint changes have rarely impacted us, but I agree in general that we do too much on prod deploys (including linting).  Ideally we'd just deploy the artifacts that are in use in staging and that would be it.

**Pull request merged**
