### PR TITLE
Enable test coverage in Code Climate

### PR DESCRIPTION
**Pull request by glewis-ANet**
* Add steps to enable code coverage reporting in Code Climate per https://docs.codeclimate.com/docs/configuring-test-coverage
* Modify the testcover job to pass through parameters to the command

Note that projects must pass their test reporter id into the testcover job for this to work.  The value for this can be found on the Code Climate project page

### CODE REVIEW

**Comment by glewis-ANet** [comment]
Note: I don't think we all have our accounts set up in Code Climate yet and it is mostly configured for the Spring Boot projects so far.  I'll try and organise the accounts.

The process of setting this up, should a project already use the Go Orb is to simply pass the test reporter id as a parameter, that triggers the integration.  That value is unique per project in Code Climate, so to have one the project must first be imported there.

**Comment by glewis-ANet** [comment]
I'll also note Code Climate does a variety of code analysis, not just test coverage tracking, so there are benefits for importing projects and it is pretty simple.  That said, it seems to pick up some false positives, at least in our Go projects.  For example, it picked up that the auto-generated mocks had a lot of repetitive code rather than ignoring them.  This is admittedly with a sample size of one Go project so far :)

**Review by xanderflood — APPROVED** [review]
I've never used code climate (except for seeing a box pop up on Java PRs) but I'm interested to see what it turns up!

**Review by caeost — APPROVED** [review]
LGTM.

I have never used Code Climate, what is this test reporter id that we need, how would i find it (or decide it?), and what does it mean to pass it to test-cover?

**Pull request merged**
